### ISSUE TITLE
Error ingesting from network source (FTP)

### ISSUE THREAD

**Issue by jusiponen** [jamiegau/cinema-catcher-app#4] opened 2023-10-18 09:51 UTC
I'm currently test driving the Catcher application with the intent of using it as a content library server.

We have two content delivery boxes (servers) from two different delivery service providers (_GoFilex_ and _Unique_). 

- _Unique_ works fine - I can get the list of assets and ingest content both manually and automatically.
- _GoFilex_ works to the point of showing the asset list, but ingest fails. Dolby DSS200 and Barco ICMP servers ingest from the same box perfectly fine.

My primary suspect is the FTP active/passive mode, but doesn't generating the asset list also access the CPL files (in addition to running directory listings recursively)? If so, then why does **that** work, but ingest fails?

I'd be happy to provide logs, etc.

![2023-10-18_12-25-06](https://github.com/jamiegau/cinema-catcher-app/assets/12255378/66e017ba-83ca-4bcd-add4-d6b147eb2ed0)

**Comment by jamiegau** [comment] 2023-10-18 11:33
Umm.  hard to know.  I have not had direct access to a Goflex box myself.

Can you tell me, when you try and download a file from Goflex, to you get any red toast-popups at the bottom right?

Otherwise, 
in /opt/cinema_catcher_app,  run
```
docker compose down
docker compose up -d

```
This will clear out all the old logs..

Go into the interface, try and transfer a DCP from the GoFlex machine..

then run
`docker compose logs > /tmp/Logs_to_post_to_github.log`

upload the log file here and I will have a look.

**Comment by jusiponen** [comment] 2023-10-18 12:36
Here are the logs from attempted ingest.

[Logs_to_post_to_github.log.gz](https://github.com/jamiegau/cinema-catcher-app/files/13024884/Logs_to_post_to_github.log.gz)

**Comment by jamiegau** [comment] 2023-10-18 14:50
Does /Gofilex/trailer/Argylle_TLR-A_F_EN-fi_FI_51_2K_UP_20230922_PXU_SMPTE_OV-79b10ac3-fe9e-4732-8a64-707b089278bb actually exist on the Gofilex machine as a DCP directory??

Try setting up a Gofilex source that points to /GoFlix/trailer   Then scan and see if you can ingest it from there.
May be a bug with deeper linking of DCP directories.

**Comment by jusiponen** [comment] 2023-10-18 17:04
Yes, the names of the DCP directories really are like that (they have a GUID appended at the end).

Setting the Path property of the asset source to /Gofilex/trailer didn't help, the ingest still failed.

**Comment by jamiegau** [comment] 2023-10-18 20:55
I'll have to make a more detailed debug version.

In the meantime, can you get me a directory listing of the folder we are looking it.

**Comment by jusiponen** [comment] 2023-10-19 19:30
Directory listing:
```
ftp> ls
200 PORT command successful
150 Opening ASCII mode data connection for file list
Argylle_TLR-A_F_EN-fi_FI_51_2K_UP_20230922_PXU_SMPTE_OV_01.mxf
Argylle_TLR-A_F_EN-XX_OV_51_2K_UP_20230913_PXU_SMPTE_OV_01_audio.mxf
PKL_716583ab-4a08-41fe-b6d2-7c221535664d.xml
CPL_d13de36a-9199-4148-9b68-7f7919e9c7cb.xml
ASSETMAP.xml
VOLINDEX.xml
226 Transfer complete
ftp: 257 bytes received in 0.01Seconds 21.42Kbytes/sec.
```

The hardware is a QNAP NAS box.

The whole FTP session:
[GitHub - GoFilex FTP test.txt](https://github.com/jamiegau/cinema-catcher-app/files/13046924/GitHub.-.GoFilex.FTP.test.txt)

**Comment by jamiegau** [comment] 2023-10-20 06:57
@jusiponen can you please update the install to the latest version. (Version: 3.4.29). use the update script in the install directory cinema-catcher-app.    Then do the same log capture you already sent me.

An exception is occuring but it appeas to have no description.  This verison just ups the verbosity.

I am also looking to get access to a similar unit here so I can test against it.

**Comment by jusiponen** [comment] 2023-10-21 15:45
Ran the new version and this bit here looked interesting:

```
cinema-catcher-app-worker-1       | INFO|20231021-15:25:06|consumers|send_message_task_status|405|send_message_task_status: bt9Y : None : Start : 0.0 : 2023-10-21 18:25:06.217896+03:00
cinema-catcher-app-worker-1       | INFO|20231021-15:25:06|consumers|send_message_task_status|405|send_message_task_status: bt9Y : None : Calculating size of download : 0 : 2023-10-21 18:25:06.257672+03:00
cinema-catcher-app-worker-1       | WARNING|20231021-15:25:06|LogActivity|LogActivityLog|18|Exception/CANCEL ftp DCP: Argylle_TLR-A_F_EN-fi_FI_51_2K_UP_20230922_PXU_SMPTE_OV, cause: None : 550 SIZE not allowed in ASCII mode
cinema-catcher-app-worker-1       | INFO|20231021-15:25:06|consumers|send_message_type_all_general|292|send_message_type_all_general: df32 : None : Exception/CANCEL ftp DCP: Argylle_TLR-A_F_EN-fi_FI_51_2K_UP_20230922_PXU_SMPTE_OV, cause: None : 550 SIZE not allowed in ASCII mode : 0.0

```
Here's a bit more before and after that message:
[GitHub - GoFilex FTP test 2.txt](https://github.com/jamiegau/cinema-catcher-app/files/13061112/GitHub.-.GoFilex.FTP.test.2.txt)

This makes sense - I mean the FTP server is supposed to convert EOL byte(s) between the source and target systems, so to return accurate size in bytes, the server would need to read the source to figure out how much EOL patching it has to do.

I'm quessing some (most?) servers just shrug and return the on-disc byte count.

**Comment by jamiegau** [comment] 2023-10-22 01:24
Yes, that's the extra debug message I added to the new you installed.
Quick googling, there is a basic fix.  I'll look at it tomorrow when I get to work.

**Comment by jamiegau** [comment] 2023-11-14 21:42
Sorry this has taken so long, but I have been doing a major upgrade to libraries in the software and it cascaded.
A fix for this issue is in the current release, however, the upgrade to more recent libraries requires me to re-write some sections.  Mainly to do with time series data.  So bandwidth measurement graphs will be broken.  But they are not essential.
I'll re-write them to the new library next week.

To upgrade, go to the cinema-catcher-app directory as root
source local.env
./upgrade.sh

**Comment by jamiegau** [comment] 2023-11-20 05:30
@jusiponen I see you updated.  Did the fix allow it to get content from the GoFilex server ok?  Has the error gone away and is it ftp downloading content from the server ok now?  Want to close of this issue.

**Comment by jusiponen** [comment] 2023-11-20 07:30
Hi James,

I finally had time to test the fix over the weekend and it works. The
ingest error is gone and catcher ingested everything from the GoFilex
server overnight.


Ystävällisin terveisin / Best Regards

Jussi Siponen
***@***.***
GSM: +358 400 767030



ma 20. marrask. 2023 klo 7.30 James Gardiner ***@***.***)
kirjoitti:

**Comment by jamiegau** [comment] 2023-11-20 08:09
thats great.

what exactly are you using it for.  What features?

Regards,
James Gardiner
[m] +61 4 12 997011

CineTechGeek
Suite 129, 9 Hall Street,
Port Melbourne, VIC 3207
[p] +61 3 9686 5415

www.digitall.net.au
<https://mailtrack.io/link/18cb4a3a6efa3bc30c3c1295217c8da06882ad69?url=http%3A%2F%2Fwww.digitall.net.au%2F&userId=7382751&signature=38e0e708b00e5c33>
  -- www.finishingroom.com.au
<https://mailtrack.io/link/56340fa9bf9274bda8651a001eff3001773f7729?url=http%3A%2F%2Fwww.finishingroom.com.au%2F&userId=7382751&signature=f158726652bf7e1e>
 -- www.clubmovie.com.au
<https://mailtrack.io/link/f631dd91d957c389a5fda200e6f618c7a1e4be55?url=http%3A%2F%2Fwww.clubmovie.com.au%2F&userId=7382751&signature=e829028e25f32912>
 -- www.cinetechgeek.com
<https://mailtrack.io/link/f07198030fd7470b20e31ed89bae2316158af821?url=http%3A%2F%2Fwww.cinetechgeek.com%2F&userId=7382751&signature=e5b6585f59ea7d39>

**Comment by jamiegau** [comment] 2023-11-20 08:09
Close this off.

**Closed by jamiegau** 2023-11-20 08:09 UTC

**Comment by jusiponen** [comment] 2023-11-20 10:32
I think this is going to re-open the Github issue, but you *did* ask about
my usage of the Catcher...

Currently I'm using it mostly as an asset library. Unique and GoFilex will
only store content for a limited amount of time and then they can erase it
to make room for new content.
So I'm ingesting everything as it gets delivered. I'm planning on letting
the Catcher to automatically manage the library, with the occasional asset
getting manually tagged as no-delete.

I've also (partially) set up AutoKDM: it works fine for the two Barco ICMP
servers we have, but not for the old Dolby DSS200 (I can't get the player
cert directly from the player or from the vendor FTP). The DSS200 is going
to be replaced with a Barco ICMP within the next six months or so, and the
problem should go away at that point.

The Catcher works great as an FTP server for the ICMPs, but not for the
DSS200 (the Show Manager application shows an error about a file not
existing in the source directory and terminates the ingest immediately).

The issues with the DSS200 limit the current usability a bit, but I don't
think it's worth it for you to spend any time or effort to fix the
compatibility issues with an obsolete piece of kit.
The issues will go away when the cinema decommissions the last DSS200.

---------
Background:
The cinema I work at used to be all DSS200 (3 screens). The built-in small
scale TMS functionality worked great for us. The Show Manager application
was a one-stop-shop for checking the status of all screens, building
playlists and schedules, and managing content (ingests and copying between
screens). KDMs had to be unzipped from email manually and uploaded to one
of the servers with FTP (that server would then distribute the keys to the
correct screens).

As far as I can tell, there's no TMS currently available that'd make sense
in such a small environment. Having a library server with auto ingest,
asset auto delete and the AutoKDM) papers over some of the functionality we
lost, and is in some areas an *improvement* over the old Dolby system.

But I do miss the old consolidated screen status view and scheduling.

Ystävällisin terveisin / Best Regards

Jussi Siponen



ma 20. marrask. 2023 klo 10.09 James Gardiner ***@***.***)
kirjoitti:

> thats great.
>
> what exactly are you using it for. What features?
>
> Regards,
> James Gardiner
> [m] +61 4 12 997011
>
> CineTechGeek
> Suite 129, 9 Hall Street,
> Port Melbourne, VIC 3207
> [p] +61 3 9686 5415
>
> www.digitall.net.au
> <
> https://mailtrack.io/link/18cb4a3a6efa3bc30c3c1295217c8da06882ad69?url=http%3A%2F%2Fwww.digitall.net.au%2F&userId=7382751&signature=38e0e708b00e5c33>
>
> -- www.finishingroom.com.au
> <
> https://mailtrack.io/link/56340fa9bf9274bda8651a001eff3001773f7729?url=http%3A%2F%2Fwww.finishingroom.com.au%2F&userId=7382751&signature=f158726652bf7e1e>
>
> -- www.clubmovie.com.au
> <
> https://mailtrack.io/link/f631dd91d957c389a5fda200e6f618c7a1e4be55?url=http%3A%2F%2Fwww.clubmovie.com.au%2F&userId=7382751&signature=e829028e25f32912>
>
> -- www.cinetechgeek.com
> <
> https://mailtrack.io/link/f07198030fd7470b20e31ed89bae2316158af821?url=http%3A%2F%2Fwww.cinetechgeek.com%2F&userId=7382751&signature=e5b6585f59ea7d39>
>
>
>

**Comment by jamiegau** [comment] 2023-11-21 21:20
Umm. yes the DSS200, is completely deprecated and has some very nasty bugs that will never get fixed...

The problem is, there is still a lot out there and cinemas are not in a position to upgrade.  Especially in this sunset period where cinema attendance is edging down.  And cinemas have not been putting money away after the last 10 years to save for a replacement.

We are definitely heading for another digital transition but with no VPF.  This equipment has a relatively short life span compared to cogs and wheel film projectors.

But yes, I have no motivation to support a DSS200 as it is an elephant.  But it SHOULD be able to FTP content from the catcher.  Maybe a simple fix could deal with that.  Get me the logs from the DSS200 on that and I'll have a quick look.

I was considering putting a TMS functionality I created for my own cinemas into catcher, but other mainstream TMS makers were going to do that for free.  "WHERE" being the point.  They have all backflipped on this promise.

I expect the contraction in the market makes it more about keeping current clients happy, no need to invest in obtaining new ones as there is very little benefit as very few cinemas are opening. (Or should be if you have any sense)

I think more will after some type of correction and change in the business model that does not push big emerald palace type cinema complexes.   Cinema will evolve to a "opera" type experience if they don;t wise up.  i.e. very expensive with a small fraction of locations we have today, only in the big cities.
